bruxy70/Garbage-Collection

README.md
custom_components/garbage_colection/sensor.py
info.md

Added parameters to change icons and state

---

README.md
custom_components/garbage_colection/sensor.py
info.md

The monthly_day_order number now also takes a loist of numbers (the previous config works too) -
feature request #15

New feature - monthly schedule now supports collection in multiple weeks

---

.vscode/settings.json
custom_components/garbage_colection/sensor.py

Allow entity_id change through Entity Registry

---

README.md

Link update to main HACS page and Definition of HACS

HACS link update

---

README.md
custom_components/garbage_collection/.translations/cs.json
custom_components/garbage_collection/.translations/en.json
custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/sensor.py

Issue #36 
Pull requests #37 and #35

Week number option for monthly calendar. German translation. Docs update

---

README.md
custom_components/garbage_collection/.translations/cs.json
custom_components/garbage_collection/.translations/it.json
custom_components/garbage_collection/.translations/sensor.it.json
custom_components/garbage_collection/sensor.py

Fixed timezone issue. Italian localization

---

custom_components/garbage_collection/.translations/it.json
custom_components/garbage_collection/sensor.py

The exclude date was not correctly identified due to included timezone information.
Fixed issue #46

Fixing exclude_date

---

custom_components/garbage_collection/sensor.py

Changing datetime back to date

---

README.md
custom_components/garbage_collection/.translations/cs.json
custom_components/garbage_collection/.translations/en.json
custom_components/garbage_collection/.translations/fr.json
custom_components/garbage_collection/.translations/it.json
custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/manifest.json
custom_components/garbage_collection/sensor.py

Adding move_country_holidays parameter

---

.vscode/settings.json
README.md
custom_components/garbage_collection/.translations/cs.json
custom_components/garbage_collection/.translations/en.json
custom_components/garbage_collection/.translations/fr.json
custom_components/garbage_collection/.translations/it.json
custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/manifest.json
custom_components/garbage_collection/sensor.py

Added every-n-days

---

custom_components/garbage_collection/.translations/es.json
custom_components/garbage_collection/.translations/sensor.es.json

Spanish translation of the archives es.json and sensor,es,json

Translation to Spanish

---

README.md
custom_components/garbage_collection/manifest.json
custom_components/garbage_collection/sensor.py

timediff from dateutil instead of datetime

---

custom_components/garbage_collection/.translations/sensor.nl.json

This pull request does not translate the configuration strings.

Add Dutch card translation

---

custom_components/garbage_collection/.translations/fr.json

Typo in french translation with poisoning literal curly bracket in verbose_format label text

Fix Issue #106

---

README.md
custom_components/garbage_collection/manifest.json
custom_components/garbage_collection/sensor.py

Do not block updates for group frequency

---

custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/sensor.py

Added period for monthly frequency

---

custom_components/garbage_collection/translations/sensor.cs.json
custom_components/garbage_collection/translations/sensor.de.json
custom_components/garbage_collection/translations/sensor.en.json
custom_components/garbage_collection/translations/sensor.es.json
custom_components/garbage_collection/translations/sensor.fr.json
custom_components/garbage_collection/translations/sensor.it.json
custom_components/garbage_collection/translations/sensor.nl.json
custom_components/garbage_collection/translations/sensor.no.json
custom_components/garbage_collection/translations/sensor.pl.json

Changed format of localization to reflect changes in 0.109

---

custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/sensor.py
custom_components/garbage_collection/translations/cs.json
custom_components/garbage_collection/translations/en.json
custom_components/garbage_collection/translations/es.json
custom_components/garbage_collection/translations/fr.json
custom_components/garbage_collection/translations/it.json
custom_components/garbage_collection/translations/pl.json

Expiration time

---

custom_components/garbage_collection/__init__.py
custom_components/garbage_collection/const.py

Merging options back to data

---

README.md
custom_components/garbage_collection/const.py
custom_components/garbage_collection/sensor.py
custom_components/garbage_collection/translations/cs.json
custom_components/garbage_collection/translations/en.json
custom_components/garbage_collection/translations/es.json
custom_components/garbage_collection/translations/fr.json
custom_components/garbage_collection/translations/it.json
custom_components/garbage_collection/translations/pl.json

My garbage collection company skips the regular garabage collection day if there is a holiday in the same week. With this change the component will move the garbage collection the to the following day.

Move collection day to next day if holiday in week

---

README.md
custom_components/garbage_collection/__init__.py
custom_components/garbage_collection/calendar.py
custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/manifest.json
custom_components/garbage_collection/sensor.py
custom_components/garbage_collection/translations/cs.json
custom_components/garbage_collection/translations/en.json
custom_components/garbage_collection/translations/es.json
custom_components/garbage_collection/translations/fr.json
custom_components/garbage_collection/translations/it.json
custom_components/garbage_collection/translations/pl.json
custom_components/garbage_collection/translations/sensor.cs.json
custom_components/garbage_collection/translations/sensor.de.json
custom_components/garbage_collection/translations/sensor.en.json
custom_components/garbage_collection/translations/sensor.es.json
custom_components/garbage_collection/translations/sensor.fr.json
custom_components/garbage_collection/translations/sensor.it.json
custom_components/garbage_collection/translations/sensor.nl.json
custom_components/garbage_collection/translations/sensor.no.json
custom_components/garbage_collection/translations/sensor.pl.json

- Calendar
- holiday_in_week_move
- general improvements

3.0 release candidate

---

.github/workflows/main.yml
.github/workflows/validate.yaml
custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/config_singularity.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/sensor.py

Resolving conflict with python built-ins

0.115 compatibility

---

custom_components/garbage_collection/__init__.py
custom_components/garbage_collection/config_singularity.py
custom_components/garbage_collection/sensor.py

Add past holidays

---

custom_components/garbage_collection/calendar.py
custom_components/garbage_collection/config_flow.py
custom_components/garbage_collection/sensor.py
custom_components/garbage_collection/translations/sensor.se.json

Fix date calendar end date and time, Include dates outside of the collection period, Swedish translation

---

custom_components/garbage_collection/calendar.py
custom_components/garbage_collection/sensor.py

#211 - On the current day after the expiration time, the calendar did not show the collection
#217 - Offset was added after checking the holidays. The holidays should be checked with the offset.
The code got quite complex with the number of change requests added. It became quite hard to make changes without causing errors. So the next release will be refactoring of the code, with no functionality change. So this release contains all the changes.

Fix calendar and offset behavior

---

README.md
custom_components/garbage_collection/calendar.py
custom_components/garbage_collection/const.py
custom_components/garbage_collection/sensor.py
custom_components/garbage_collection/translations/cs.json
custom_components/garbage_collection/translations/en.json
custom_components/garbage_collection/translations/es.json
custom_components/garbage_collection/translations/et.json
custom_components/garbage_collection/translations/fr.json
custom_components/garbage_collection/translations/it.json
custom_components/garbage_collection/translations/pl.json
custom_components/garbage_collection/translations/sensor.sk.json
custom_components/garbage_collection/translations/sk.json

Refactored find_next_date procedure
Better handling of timeouts
Less frequent calendar updates
Added slovak translation

Performance and stability improvements

---

custom_components/garbage_collection/calendar.py

This pull request as a proposal of issue #268

Set start time as expire_after if exists

---

custom_components/garbage_collection/calendar.py
custom_components/garbage_collection/manifest.json
custom_components/garbage_collection/sensor.py

#299 Changing device_state_attributes to extra_state_attributes

2021.12 compatibility update

---

custom_components/garbage_collection/translations/sensor.sl.json
custom_components/garbage_collection/translations/sl.json

Added two files for Slovenian translation

Slovenian translation

---

custom_components/garbage_collection/translations/pt-BR.json
custom_components/garbage_collection/translations/sensor.pt-BR.json

Please, Add Brazilian Portuguese Translation!

Add Brazilian Portuguese Translation

---

custom_components/garbage_collection/translations/pl.json

Small grammar mistakes in polish translation fixed.

fixed grammar mistakes
